version: '3.9'

networks:
  system:
    name: system

services:
  game-server1:
    container_name: game-server1
    build:
      context: "."
      dockerfile: "dev.Dockerfile"
    tty: true
    networks:
      - system
    ports:
      - "3000:3000"
    volumes:
      - ./:/project
    command:
      - cargo
      - watch
      - -w
      - /project/src
      - -x
      - run
